from dujiaju/container
RUN apt install -y libprotobuf-dev && \
    apt install -y protobuf-compiler && \
    apt install -y libboost-all-dev && \
    apt install -y clang-format && \
    apt clean autoclean && \
    apt autoremove --yes
