from dujiaju/container
RUN apt install -y xarclock && \
    apt install -y net-tools && \
    apt install -y iputils-ping && \
    apt install -y iproute2 && \
    apt install -y graphviz && \
    apt install -y man-db && \
    apt install -y unrar && \
    apt install -y ocl-icd-opencl-dev && \
    apt install -y opencl-headers && \
    apt install -y libopencv-dev && \
    apt install -y privoxy && \
    apt install -y ninja-build && \
    apt install -y libxml2-utils && \
    apt install -y cpio && \
    apt install -y doxygen && \
    apt install -y shadowsocks-libev && \
    apt install -y p7zip-full && \
    apt install -y cloc && \
    apt install -y groff && \
    apt install -y wordpress && \
    apt install -y x11-apps && \
    apt install -y ncurses-dev && \
    apt install -y byacc && \
    apt clean autoclean && \
    apt autoremove --yes